name: ✨ 機能
description: 新機能を記録する
labels: ["feature"]
projects: ["hasegawa496/12"]
assignees: ["hasegawa496"]

body:
  - type: markdown
    attributes:
      value: |
        この Issue は作成時に Project（`hasegawa496/12`）へ自動で追加されます（権限の都合で追加されない場合があります）。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 未定
        - "P0: 緊急"
        - "P1: 高"
        - "P2: 中"
        - "P3: 低"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - XS
        - S
        - M
        - L
        - XL
      default: 2
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 概要
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用シーン
    validations:
      required: false

  - type: textarea
    id: note
    attributes:
      label: メモ
    validations:
      required: false
