# ShellCheck（配布先へコピーして使う workflow）
#
# 推奨:
#   - このファイルを対象リポジトリの `.github/workflows/shellcheck-ci.yml` としてコピーしてください。

name: ShellCheck

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  shellcheck:
    uses: hasegawa496/.github/.github/workflows/shellcheck.yml@main
